updates

diff --git a/test/testall.sh.in b/test/testall.sh.in
--- a/test/testall.sh.in
+++ b/test/testall.sh.in
@@ -4,15 +4,9 @@
 # tee output to testdetails.log
 if ( test "$CHILD" != "1" )
 then
-	#FIFO=testall.fifo
-	#rm -f $FIFO
-	#mkfifo $FIFO
-	#CHILD=1 $0 $* > $FIFO 2>&1 &
 	CHILD=1 $0 2>&1 | tee testdetails.log &
 	PID=$!
-	#tee testdetails.log <$FIFO &
 	wait $PID
-	#rm -f $FIFO
 	exit $?
 fi
 
@@ -42,36 +36,35 @@ fi
 sleep 2
 
 # for each database/configuration...
-for DB in  @TESTDBS@
+for DB in @TESTDBS@
 do
 
-	# for tls, krb, and extensions tests, verify that we support oracle
-	if ( test "$DB" = "tls" -o "$DB" = "krb" -o "$DB" = "extensions" )
+	# make sure that support for the appropriate database exists
+	MODULE=$DB
+	case "$DB" in
+		tls|krb|extensions)
+			MODULE=oracle
+			;;
+		mysql*)
+			MODULE=mysql
+			;;
+		postgresql*)
+			MODULE=postgresql
+			;;
+	esac
+	if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_$MODULE.* 2> /dev/null`" )
 	then
-		if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_oracle.so 2> /dev/null`" )
-		then
-			echo "skipping $DB..."
-			echo
-			echo "================================================================================"
-			echo
-			continue
-		fi
+		echo "skipping $DB..."
+		echo
+		echo "================================================================================"
+		echo
+		continue
+	fi
 
-	# for the mysqlprotocol test, verify that we support the mysql
-	elif ( test "$DB" = "mysqlprotocol" )
+	# for router tests, also verify that we support mysql
+	if ( test "$DB" = "router" )
 	then
-		if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_mysql.so 2> /dev/null`" )
-		then
-			echo "skipping $DB..."
-			echo
-			echo "================================================================================"
-			echo
-			continue
-		fi
-
-	# for other tests, verify that we support the database
-	else
-		if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_$DB.so 2> /dev/null`" )
+		if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_mysql.* 2> /dev/null`" )
 		then
 			echo "skipping $DB..."
 			echo
@@ -81,10 +74,10 @@ do
 		fi
 	fi
 
-	# for router tests, also verify that we support mysql
-	if ( test "$DB" = "router" )
+	# for mssql tests, also verify that we have an odbc config for it
+	if ( test "$DB" = "mssql" )
 	then
-		if ( test -z "`ls $PREFIX/lib*/sqlrelay/sqlrconnection_mysql.so 2> /dev/null`" )
+		if ( test -z "`grep mssqlodbc /etc/odbc.ini 2> /dev/null`" )
 		then
 			echo "skipping $DB..."
 			echo
@@ -101,15 +94,15 @@ do
 	# for the router test, start the master/slave instances
 	if ( test "$DB" = "router" )
 	then
-		$PREFIX/bin/sqlr-start -config `pwd`/sqlrelay.conf -id routermaster -backtrace `pwd`
+		$PREFIX/bin/sqlr-start -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id routermaster -backtrace @abs_top_builddir@/test
 		sleep 2
 
-		$PREFIX/bin/sqlr-start -config `pwd`/sqlrelay.conf -id routerslave -backtrace `pwd`
+		$PREFIX/bin/sqlr-start -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id routerslave -backtrace @abs_top_builddir@/test
 		sleep 2
 	fi
 
 	# start the instance
-	$PREFIX/bin/sqlr-start -config `pwd`/sqlrelay.conf -id ${DB}test -backtrace `pwd`
+	$PREFIX/bin/sqlr-start -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id ${DB}test -backtrace @abs_top_builddir@/test
 	sleep 2
 
 	# make sure that the instance is up
@@ -121,7 +114,7 @@ do
 		echo "pinging $DB..."
 		if ( test "$DB" = "tls" )
 		then
-			PING=`$PREFIX/bin/sqlrsh -host localhost -tls -tlscert $PREFIX/etc/sqlrelay.conf.d/client.pem -tlsca $PREFIX/etc/sqlrelay.conf.d/ca.pem -tlsvalidate ca -command ping 2>&1`
+			PING=`$PREFIX/bin/sqlrsh -host localhost -tls -tlscert @abs_top_builddir@/test/sqlrelay.conf.d/tls/client.pem -tlsca @abs_top_builddir@/test/sqlrelay.conf.d/tls/ca.pem -tlsvalidate ca -command ping 2>&1`
 		elif ( test "$DB" = "extensions" )
 		then
 			PING=`$PREFIX/bin/sqlrsh -host localhost -user test -password test -command ping 2>&1`
@@ -132,8 +125,15 @@ do
 			then
 				PING="The database is up."
 			fi
+		elif ( test "$DB" = "postgresqlprotocol" )
+		then
+			PING="0: Couldn't connect to the listener."
+			if ( test -n "`netstat -an 2> /dev/null | grep LISTEN | grep 5432`" )
+			then
+				PING="The database is up."
+			fi
 		else
-			PING=`$PREFIX/bin/sqlrsh -id ${DB}test -command ping 2>&1`
+			PING=`$PREFIX/bin/sqlrsh -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id ${DB}test -command ping 2>&1`
 		fi
 
 		# (this collapses whitespace)
@@ -178,13 +178,26 @@ do
 
 			if ( test "$DB" = "mysqlprotocol" )
 			then
-				./dropin/mysql
+				cd protocol/mysql
+				./mysql
 				if ( test "$?" = "0" )
 				then
-					printf "    % 8s: success\n" "dropin" >> testresults.log
+					printf "    % 8s: success\n" "protocol" >> ../../testresults.log
 				else
-					printf "    % 8s: failed\n" "dropin" >> testresults.log
+					printf "    % 8s: failed\n" "protocol" >> ../../testresults.log
 				fi
+				cd ../..
+			elif ( test "$DB" = "postgresqlprotocol" )
+			then
+				cd protocol/postgresql
+				./postgresql
+				if ( test "$?" = "0" )
+				then
+					printf "    % 8s: success\n" "protocol" >> ../../testresults.log
+				else
+					printf "    % 8s: failed\n" "protocol" >> ../../testresults.log
+				fi
+				cd ../..
 			else
 				./test.sh $DB
 			fi
@@ -200,13 +213,15 @@ do
 	if ( test "$DB" = "router" )
 	then
 		sleep 2
-		$PREFIX/bin/sqlr-stop -config `pwd`/sqlrelay.conf -id routermaster
+		$PREFIX/bin/sqlr-stop -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id routermaster
 		sleep 2
-		$PREFIX/bin/sqlr-stop -config `pwd`/sqlrelay.conf -id routerslave
+		$PREFIX/bin/sqlr-stop -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id routerslave
 	fi
 	sleep 2
-	$PREFIX/bin/sqlr-stop -config `pwd`/sqlrelay.conf -id ${DB}test
+	$PREFIX/bin/sqlr-stop -config @abs_top_builddir@/test/sqlrelay.conf.d/${DB}.conf -id ${DB}test
 	sleep 2
+
+	rm -f log/*.log
 
 	echo
 	echo "================================================================================"
